name = "registry-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-29"
[[kv_namespaces]]
binding = "REGISTRY_MAPS"
id = "7e3d3c54ddfb4fd69e5736164696488a"
[dev]
ip = "127.0.0.1"
port = 8888
local_protocol = "https"
